// Opciones de tipos de equipo (orden alfabético, "Otro" al final)
export const TIPO_EQUIPO_OPTIONS = [
  "Amasadora",
  "Báscula",
  "Batidora",
  "Congelador",
  "Cortapollos",
  "Crepera",
  "Despachador de Bebidas",
  "Empacadora",
  "Extractor",
  "Fábrica de Hielo",
  "Freidora",
  "Horno",
  "Lavavajillas",
  "Licuadora",
  "Marinadora",
  "Mesa Fría",
  "Microondas",
  "Molino",
  "Palomera",
  "Paninera",
  "Procesador de Vegetales",
  "Rebanadora",
  "Refrigerador",
  "Rosticero",
  "Sierra",
  "Termoselladora",
  "Turbolicuador",
  "Vitrina",
  "Waflera",
  "Otro",
];

// Opciones de marcas (orden alfabético, "Otro" al final)
export const MARCA_OPTIONS = [
  "Blazer",
  "Coriat",
  "Euroquip",
  "Exmex",
  "Fabatsa",
  "Imbera",
  "International",
  "JR",
  "Mexcut",
  "MG",
  "Migsa",
  "Ojeda",
  "Polar",
  "Protek",
  "Rhino",
  "Sammic",
  "Tapisa",
  "Tecnikitchen",
  "Torrey",
  "Otro",
];
